### PR TITLE
Added files

### PR DESCRIPTION
**Pull request by chethan1801**

### CODE REVIEW

**Comment by codekaka** [comment]
Pull request was made succesfully and this is a large sized Pull Request.Do you want me to run any or all of the following analysis?
                    
s1: Code coverage
                    s2: Code Duplication
                    s3: Dependency Analysis
                    s4: Documentation
                    run all: To run all the above analysis
                    
Please reply with s1, s2, s3, s4 or 'run all' for the respective analysis
                    Example 1: To run Code coverage, Code Duplication, reply with "run s1,s2"
                    Example 2: To run all the analysis, reply with "run all".
                    Note: Reply commands are not case sensitive.

**Comment by chethan1801** [comment]
@codekaka run all

**Comment by codekaka** [comment]
Ran all the analysis and here are the results:

CODE DOCUMENTATION RESULTS:
-----------------------
README.md(3)                                                     Library Functions Manual                                                     README.md(3)



NAME
       README.md -

SYNOPSIS
Author
       Generated by CRABOT.



README.md(3)                                                     Library Functions Manual                                                     README.md(3)



NAME
       README.md -

SYNOPSIS
Author
       Generated by CRABOT.



README.md(3)                                                     Library Functions Manual                                                     README.md(3)



NAME
       README.md -

SYNOPSIS
Author
       Generated by CRABOT.



com.github.maven.example.Widget(3)                               Library Functions Manual                               com.github.maven.example.Widget(3)



NAME
       com.github.maven.example.Widget -

SYNOPSIS
   Public Member Functions
       Widget ()
       boolean isEnabled ()
       Widget setEnabled (boolean enabled)
       boolean testIsEnabled ()
       Widget testSetEnabled (boolean enabled)

   Private Attributes
       boolean enabled

Detailed Description
       Simple wigdet class that can be enabled or disabled

Constructor & Destructor Documentation
   com.github.maven.example.Widget.Widget () [inline]
       Create new enabled widget

Member Function Documentation
   boolean com.github.maven.example.Widget.isEnabled () [inline]
       Is the widget currently enabled?

       Returns:
           true if enabled, false otherwise

   Widget com.github.maven.example.Widget.setEnabled (booleanenabled) [inline]
       Set the widget enable state

       Parameters:
           enabled

       Returns:
           this widget

   boolean com.github.maven.example.Widget.testIsEnabled () [inline]
       Is the widget currently enabled?

       Returns:
           true if enabled, false otherwise

   Widget com.github.maven.example.Widget.testSetEnabled (booleanenabled) [inline]
       Set the widget enable state

       Parameters:
           enabled

       Returns:
           this widget

Member Data Documentation
   boolean com.github.maven.example.Widget.enabled [private]
Author
       Generated by CRABOT.



com.github.maven.example.tests.WidgetTest(3)                     Library Functions Manual                     com.github.maven.example.tests.WidgetTest(3)



NAME
       com.github.maven.example.tests.WidgetTest -

SYNOPSIS
   Public Member Functions
       void defaultState ()
       void updateEnableState ()

Detailed Description
       Unit tests of Widget class

Member Function Documentation
   void com.github.maven.example.tests.WidgetTest.defaultState () [inline]
       Test default enable state of Widget

   void com.github.maven.example.tests.WidgetTest.updateEnableState () [inline]
       Test enabling and disabling a Widget


Author
       Generated by CRABOT.



My Project                                                            Tue Nov 29 2016                         com.github.maven.example.tests.WidgetTest(3)

CODE COVERAGE CHECK RESULTS:
-----------------------

Line Coverage: 66%
Branch Coverage: 66%


CODE DUPLICATE CHECK RESULTS:
-----------------------

No duplicates found for file: src/test/java/com/github/maven/example/tests/WidgetTest.java

CODE DEPENDENCY CHECK RESULTS:
-----------------------

DEPENDENCY CHANGE ANALYSIS:
Added Dependencies are:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.github.kevinsawicki</groupId>
	<artifactId>github-maven-example</artifactId>
	<version>0.1-SNAPSHOT</version>
	<name>GitHub Maven Plugin Example</name>
	<description>Project to demonstrate GitHub Maven plugins</description>
	<url>https://github.com/kevinsawicki/github-maven-example</url>

	<issueManagement>
		<url>https://github.com/kevinsawicki/github-maven-example/issues</url>
		<system>GitHub Issues</system>
	</issueManagement>

	<licenses>
		<license>
			<name>MIT License</name>
			<url>http://www.opensource.org/licenses/mit-license.php</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<scm>
		<url>https://github.com/kevinsawicki/github-maven-example</url>
		<connection>scm:git:git://github.com/kevinsawicki/github-maven-example.git</connection>
		<developerConnection>scm:git:git@github.com:kevinsawicki/github-maven-example.git</developerConnection>
	</scm>

	<developers>
		<developer>
			<email>kevinsawicki@gmail.com</email>
			<name>Kevin Sawicki</name>
			<url>https://github.com/kevinsawicki</url>
			<id>kevinsawicki</id>
		</developer>
	</developers>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>com.github.github</groupId>
				<artifactId>downloads-maven-plugin</artifactId>
				<version>0.6</version>
				<configuration>
					<description>Official ${project.name} build of the ${project.version} release</description>
					<override>true</override>
					<includeAttached>true</includeAttached>
					<server>github</server>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>upload</goal>
						</goals>
						<phase>install</phase>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.github.github</groupId>
				<artifactId>site-maven-plugin</artifactId>
				<version>0.7</version>
				<configuration>
					<message>Building site for ${project.version}</message>
					<server>github</server>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>site</goal>
						</goals>
						<phase>site</phase>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-site-plugin</artifactId>
				<version>3.0</version>
				<configuration>
					<reportPlugins>
						<plugin>
							<groupId>org.apache.maven.plugins</groupId>
							<artifactId>maven-project-info-reports-plugin</artifactId>
							<version>2.2</version>
							<configuration>
								<dependencyDetailsEnabled>true</dependencyDetailsEnabled>
								<dependencyLocationsEnabled>true</dependencyLocationsEnabled>
							</configuration>
						</plugin>
						<plugin>
							<groupId>org.apache.maven.plugins</groupId>
							<artifactId>maven-javadoc-plugin</artifactId>
							<version>2.7</version>
						</plugin>
						<plugin>
							<groupId>org.apache.maven.plugins</groupId>
							<artifactId>maven-surefire-report-plugin</artifactId>
							<version>2.6</version>
						</plugin>
						<plugin>
							<groupId>org.apache.maven.plugins</groupId>
							<artifactId>maven-checkstyle-plugin</artifactId>
							<version>2.6</version>
						</plugin>
					</reportPlugins>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
							<addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
						</manifest>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.8</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>

```

**Comment by codekaka** [comment]
Pull request was made succesfully and this is a large sized Pull Request.Do you want me to run any or all of the following analysis?
                    
s1: Code coverage
                    s2: Code Duplication
                    s3: Dependency Analysis
                    s4: Documentation
                    run all: To run all the above analysis
                    
Please reply with s1, s2, s3, s4 or 'run all' for the respective analysis
                    Example 1: To run Code coverage, Code Duplication, reply with "run s1,s2"
                    Example 2: To run all the analysis, reply with "run all".
                    Note: Reply commands are not case sensitive.

**Pull request closed without merging**
